### ISSUE TITLE
global is not defined when building with Vite

### ISSUE THREAD

**Issue by ctholho** [erikh2000/web-enc-at-rest#14]
**Describe the bug**
Using web-enc-at-rest `open()` function in Vue with Vite returns an error: `Uncaught (in promise) ReferenceError: global is not defined.
<img width="904" alt="Screenshot 2023-04-03 at 14 42 25" src="https://user-images.githubusercontent.com/28910105/229563629-39a20977-19b4-4b43-bc28-bddde4c5e32b.png">

**To Reproduce**
[See Vite Stackblitz with Vue](https://stackblitz.com/edit/vitejs-vite-zk2d8u?file=src/App.vue)
[See Vite Stackblitz with React](https://stackblitz.com/edit/vitejs-vite-ca8xas?file=src/App.tsx)

This error does not reproduce when using Vue with webpack. [See this working Stackblitz with Vue and Webpack](https://stackblitz.com/edit/vue-sixxpz?file=src/App.vue)

**Additional context**
Tested with Safari and Chrome on macOS.

I found that replacing all occurrences of `global` in web-enc-at-rest's source code with `globalThis` fixed the problem and I could use web-enc-at-rest with Vite.

**Comment by erikh2000** [comment]
@ctholho , thanks for the great write-up. I repeated your `global` -> `globalThis` fix and published WEaR 1.0.2 which includes it. If you see further problems, just let me know.
