### ISSUE TITLE
Disable _productionUseWarning

### ISSUE THREAD

**Issue by ctholho** [erikh2000/web-enc-at-rest#15]
**Readme Check**
yes

**Propose Your Feature**

It's not exactly a bug, but I think it's time to disable the production use warning. :) Especially because it says
"WEaR is in a peer review period. Production use is not recommended for any WEaR package version < 1.0.0." and the version is > 1.0.0

**Comment by erikh2000** [comment]
Ah, great catch! Thanks for the PR.
